eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8000
management:
  endpoint:
    web:
      exposer:
        include: "*"

